language: node_js
node_js:
  - '8'
addons:
  chrome: stable
branches:
  - develop
  - /^release-[0-999].[0-999]$/
  - master
notifications:
  email:
    recipients:
      - tomini18@hotmail.com
script:
  - ng test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - ng e2e --protractor-config=e2e/protractor-travis.conf.js

# Deploy https://pr-mdw-agiles-front.herokuapp.com/
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU
  on:
    branch: master

